on:
  push:
    branches:
      - development
name: Deploy website on push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
      - uses: actions/checkout@v3

      - name: Use Node.js 20.5.0
        uses: actions/setup-node@v2
        with:
          node-version: "20.5.0"

      - name: Build Project
        run: |
          npm install
          npm run build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.4
        with:
          server: ${{ secrets.GIT_CPANEL_REACT_SERVER }}
          username: ${{ secrets.GIT_CPANEL_REACT_USERNAME }}
          password: ${{ secrets.GIT_CPANEL_REACT_PASSWORD }}
          protocol: ${{ secrets.GIT_CPANEL_REACT_PROTOCOL}}
          server-dir: /public_html
          local-dir: ./build
